local_costmap:
  update_frequency: 5.0
  publish_frequency: 2.0
  transform_tolerance: 0.5

  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  origin_x: -1.0
  origin_y: -1.0
  resolution: 0.01
  plugins:
    - {name: obstacle_layer,         type: "mw_costmap::ObstacleLayer"}
    - {name: inflation_layer,         type: "mw_costmap::InflationLayer"}
  
  inflation_layer:
    cost_scaling_factor: 3.0
    inflation_radius: 0.1
