map_frame: map
robot_frame: base_link
loop_frequency: 20.0
max_time_lag: 0.5
decay: 0.9
planner: "NavfnPlanner" # "NavfnPlanner" "genroute"
controller: "trajectory_planner" # "trajectory_planner" "mw_maxl_planner" "teb_local_planner" "pure_pursuit_controller"
plan_topic: "/plan"
cmd_vel_topic: "/cmd_vel"
route_topic: "/route"
goal_queue_topic: "/goal_queue"
tf_timeout: 2.0
max_retries: 2
min_distance_tolerance: 0.05
min_angular_tolerance: 0.15
controller_reset_timeout: 20.0
# recovery timeouts
recoveries:
  clear_costmap: 5.0
  rotate: 6.0
  replan: 8.0
  back_up: 10.0
  stepback_and_steerturn: 12.0

# should goals be added in a queue (true), 
# or should new goal replace the old goal (false) 
goal_queue_mode: true
